export const SDK_SURFACE = {
  initialize: [
    "getInitializeInstruction",
    "findPhygitalTokenPda",
    "parseSecp256r1Pubkey",
    "ADMIN",
    "INITIALIZE_MULTISIG_PDA",
  ],
  setMint: [
    "getSetMintInstruction",
    "findPhygitalTokenPda",
  ],
  transfer: [
    "beginTransfer",
    "authenticatePasskeyForTransfer",
    "completeTransfer",
  ],
  removeOwnership: ["getRemoveOwnershipInstruction"],
  verifyComposable: [
    "buildMessageHash",
    "authenticatePasskeyForSecp256r1Verify",
    "buildSecp256r1VerifyInstruction",
  ],
  verification: ["startAuthentication", "verifyResponse"],
  onChainComposition: {
    client: [
      "buildMessageHash",
      "authenticatePasskeyForSecp256r1Verify",
      "buildSecp256r1VerifyInstruction",
    ],
    transaction: ["secp256r1_verify", "your_program_instruction"],
    program: "CPI verify via VerifyCpiBuilder",
  },
  tokenLookup: [
    "findPhygitalTokenPda",
    "fetchPhygitalTokensByOwner",
    "fetchPhygitalTokenByIdentifier",
    "fetchPhygitalTokenByMint",
  ],
  web3js: [
    "toRpc",
    "toAddress",
    "toTransactionSigner",
    "toWeb3Instruction",
    "toWeb3Instructions",
  ],
  generated: [
    "getInitializeInstruction",
    "getTransferOwnershipInstruction",
    "getVerifyInstruction",
    "getRemoveOwnershipInstruction",
    "getSetLockStateInstruction",
    "getSetMintInstruction",
    "fetchPhygitalToken",
    "PhygitalToken",
    "PhygitalTokenType",
  ],
  rustClient: {
    crate: "phygital-token-client",
    path: "clients/rust/phygital-token",
    cpi: [
      "VerifyCpi",
      "VerifyCpiBuilder",
      "VerifyInstructionArgs",
      "SetMintCpi",
      "SetMintCpiBuilder",
      "TransferOwnershipCpi",
      "TransferOwnershipCpiBuilder",
      "RemoveOwnershipCpi",
      "RemoveOwnershipCpiBuilder",
    ],
    types: ["PhygitalToken", "Secp256r1VerifyArgs", "PhygitalTokenType"],
  },
} as const;
