use anchor_lang::prelude::*;
use anchor_lang::system_program::{create_account, CreateAccount};
use anchor_spl::token_2022::{self, initialize_mint2, InitializeMint2};
use anchor_spl::token_2022_extensions::{
    group_pointer_initialize, metadata_pointer_initialize, token_group_initialize,
    token_metadata_initialize, token_metadata_update_field, GroupPointerInitialize,
    MetadataPointerInitialize, TokenGroupInitialize, TokenMetadataInitialize,
    TokenMetadataUpdateField,
};
use anchor_spl::token_interface::TokenInterface;
use spl_token_metadata_interface::state::{Field, TokenMetadata};

use crate::constants::PROGRAM_AUTHORITY_SEED;
use crate::error::TokenProgramError;
use crate::state::DomainConfig;
use crate::utils::{
    collection_mint_layout, validate_metadata_strings, DOMAIN_CONFIG_METADATA_KEY,
    ROYALTY_BPS_METADATA_KEY, ROYALTY_OWNER_METADATA_KEY,
};

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct CreateGroupTokenArgs {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub royalty_bps: u16,
    /// Maximum number of NFTs that can join this collection.
    pub max_size: u64,
}

#[derive(Accounts)]
#[instruction(args: CreateGroupTokenArgs)]
pub struct CreateGroupToken<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    /// Collection owner — receives royalties on secondary sales.
    pub owner: Signer<'info>,

    /// New collection mint keypair — generated by caller.
    #[account(mut)]
    pub group_mint: Signer<'info>,

    pub domain_config: Account<'info, DomainConfig>,

    #[account(
        seeds = [PROGRAM_AUTHORITY_SEED],
        bump,
    )]
    pub program_authority: SystemAccount<'info>,

    pub token_program: Interface<'info, TokenInterface>,
    pub system_program: Program<'info, System>,
}

pub fn handler(ctx: Context<CreateGroupToken>, args: CreateGroupTokenArgs) -> Result<()> {
    require!(
        args.royalty_bps <= 10_000,
        TokenProgramError::InvalidRoyaltyBps
    );
    validate_metadata_strings(&args.name, &args.symbol, &args.uri)?;

    let group_mint_key = ctx.accounts.group_mint.key();
    let domain_config_key = ctx.accounts.domain_config.key();

    let mut metadata = TokenMetadata {
        name: args.name.clone(),
        symbol: args.symbol.clone(),
        uri: args.uri.clone(),
        ..Default::default()
    };
    metadata.additional_metadata.push((
        DOMAIN_CONFIG_METADATA_KEY.to_string(),
        domain_config_key.to_string(),
    ));
    metadata.additional_metadata.push((
        ROYALTY_OWNER_METADATA_KEY.to_string(),
        ctx.accounts.owner.key().to_string(),
    ));
    metadata.additional_metadata.push((
        ROYALTY_BPS_METADATA_KEY.to_string(),
        args.royalty_bps.to_string(),
    ));
    let metadata_size = metadata.tlv_size_of().unwrap();

    let layout = collection_mint_layout(metadata_size)?;

    let token_program_id = ctx.accounts.token_program.key();

    create_account(
        CpiContext::new(
            ctx.accounts.system_program.key(),
            CreateAccount {
                from: ctx.accounts.payer.to_account_info(),
                to: ctx.accounts.group_mint.to_account_info(),
            },
        ),
        layout.rent_lamports,
        layout.initial_data_len as u64,
        &token_2022::ID,
    )?;

    let token_program = ctx.accounts.token_program.to_account_info();
    let mint = ctx.accounts.group_mint.to_account_info();

    metadata_pointer_initialize(
        CpiContext::new(
            token_program_id,
            MetadataPointerInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        Some(ctx.accounts.owner.key()),
        Some(group_mint_key),
    )?;

    group_pointer_initialize(
        CpiContext::new(
            token_program_id,
            GroupPointerInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        Some(ctx.accounts.owner.key()),
        Some(group_mint_key),
    )?;

    initialize_mint2(
        CpiContext::new(token_program_id, InitializeMint2 { mint: mint.clone() }),
        0,
        &ctx.accounts.owner.key(),
        None,
    )?;

    // `program_authority` is the TokenGroup update authority — used only when
    // adding/removing collection members (`create_token`). Royalty and domain
    // metadata are owned by the collection mint authority (`owner`).
    token_group_initialize(
        CpiContext::new(
            token_program_id,
            TokenGroupInitialize {
                program_id: token_program.clone(),
                group: mint.clone(),
                mint: mint.clone(),
                mint_authority: ctx.accounts.owner.to_account_info(),
            },
        ),
        Some(ctx.accounts.program_authority.key()),
        args.max_size,
    )?;

    token_metadata_initialize(
        CpiContext::new(
            token_program_id,
            TokenMetadataInitialize {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.owner.to_account_info(),
                mint_authority: ctx.accounts.owner.to_account_info(),
                mint: mint.clone(),
            },
        ),
        args.name,
        args.symbol,
        args.uri,
    )?;

    token_metadata_update_field(
        CpiContext::new(
            token_program_id,
            TokenMetadataUpdateField {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.owner.to_account_info(),
            },
        ),
        Field::Key(DOMAIN_CONFIG_METADATA_KEY.to_string()),
        domain_config_key.to_string(),
    )?;

    token_metadata_update_field(
        CpiContext::new(
            token_program_id,
            TokenMetadataUpdateField {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.owner.to_account_info(),
            },
        ),
        Field::Key(ROYALTY_OWNER_METADATA_KEY.to_string()),
        ctx.accounts.owner.key().to_string(),
    )?;

    token_metadata_update_field(
        CpiContext::new(
            token_program_id,
            TokenMetadataUpdateField {
                program_id: token_program.clone(),
                metadata: mint,
                update_authority: ctx.accounts.owner.to_account_info(),
            },
        ),
        Field::Key(ROYALTY_BPS_METADATA_KEY.to_string()),
        args.royalty_bps.to_string(),
    )?;

    Ok(())
}
