use anchor_lang::prelude::*;
use anchor_lang::system_program::{create_account, CreateAccount};
use anchor_spl::associated_token::{self, AssociatedToken, Create};
use anchor_spl::token_2022::spl_token_2022::instruction::AuthorityType;
use anchor_spl::token_2022::{
    self, initialize_mint2, mint_to, set_authority, InitializeMint2, MintTo, SetAuthority,
};
use anchor_spl::token_2022_extensions::{
    group_member_pointer_initialize, metadata_pointer_initialize, permanent_delegate_initialize,
    token_member_initialize, token_metadata_initialize, token_metadata_update_field,
    transfer_hook_initialize, GroupMemberPointerInitialize, MetadataPointerInitialize,
    PermanentDelegateInitialize, TokenMemberInitialize, TokenMetadataInitialize,
    TokenMetadataUpdateField, TransferHookInitialize,
};
use anchor_spl::token_interface::{Mint, TokenInterface};
use spl_token_metadata_interface::state::Field;

use crate::constants::{PROGRAM_AUTHORITY_SEED, TRANSFER_HOOK_PROGRAM_ID};
use crate::utils::{
    encode_secp256r1_pubkey, initial_last_transfer_slot_value, member_mint_layout,
    member_mint_metadata_tlv_size, transfer_config_placeholder_fields,
    validate_collection_group_mint, validate_metadata_strings, LAST_TRANSFER_SLOT_METADATA_KEY,
    SECP256R1_METADATA_KEY,
};
use crate::Secp256r1Pubkey;

#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct CreateTokenArgs {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    pub secp256r1_pubkey: Secp256r1Pubkey,
}

#[derive(Accounts)]
#[instruction(args: CreateTokenArgs)]
pub struct CreateToken<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    pub owner: Signer<'info>,

    /// New token mint keypair — generated by caller
    #[account(mut)]
    pub token_mint: Signer<'info>,

    /// The group this token will be a member of
    #[account(mut)]
    pub group_mint: Box<InterfaceAccount<'info, Mint>>,

    /// Program-level PDA — permanent delegate, transfer hook authority.
    /// Writable because it signs Token-2022 CPIs that may debit its lamports.
    #[account(
        mut,
        seeds = [PROGRAM_AUTHORITY_SEED],
        bump,
    )]
    pub program_authority: SystemAccount<'info>,

    /// Owner ATA — created in the handler after the mint exists.
    /// CHECK: initialized via associated_token::create_idempotent
    #[account(mut)]
    pub owner_token_account: UncheckedAccount<'info>,
    
    #[account(
        address = token_2022::ID
    )]
    pub token_program: Interface<'info, TokenInterface>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}

pub fn handler(ctx: Context<CreateToken>, args: CreateTokenArgs) -> Result<()> {
    validate_metadata_strings(&args.name, &args.symbol, &args.uri)?;
    validate_collection_group_mint(
        &ctx.accounts.group_mint.to_account_info(),
        ctx.accounts.program_authority.key(),
    )?;

    let token_mint_key = ctx.accounts.token_mint.key();
    let program_authority_bump = ctx.bumps.program_authority;
    let bump_seed = [program_authority_bump];
    let authority_seed_array = [PROGRAM_AUTHORITY_SEED, &bump_seed[..]];
    let authority_seeds: &[&[u8]] = authority_seed_array.as_slice();
    let signer_seed_array = [authority_seeds];
    let signer_seeds: &[&[&[u8]]] = signer_seed_array.as_slice();

    let secp_pubkey_b64 = encode_secp256r1_pubkey(&args.secp256r1_pubkey);
    let metadata_size =
        member_mint_metadata_tlv_size(&args.name, &args.symbol, &args.uri, &secp_pubkey_b64)?;

    let layout = member_mint_layout(metadata_size)?;

    let token_program_id = ctx.accounts.token_program.key();

    create_account(
        CpiContext::new(
            ctx.accounts.system_program.key(),
            CreateAccount {
                from: ctx.accounts.payer.to_account_info(),
                to: ctx.accounts.token_mint.to_account_info(),
            },
        ),
        layout.rent_lamports,
        layout.initial_data_len as u64,
        &token_2022::ID,
    )?;

    let token_program = ctx.accounts.token_program.to_account_info();
    let mint = ctx.accounts.token_mint.to_account_info();

    metadata_pointer_initialize(
        CpiContext::new(
            token_program_id,
            MetadataPointerInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        Some(ctx.accounts.program_authority.key()),
        Some(token_mint_key),
    )?;

    transfer_hook_initialize(
        CpiContext::new(
            token_program_id,
            TransferHookInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        Some(ctx.accounts.program_authority.key()),
        Some(TRANSFER_HOOK_PROGRAM_ID),
    )?;

    permanent_delegate_initialize(
        CpiContext::new(
            token_program_id,
            PermanentDelegateInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        &ctx.accounts.program_authority.key(),
    )?;

    group_member_pointer_initialize(
        CpiContext::new(
            token_program_id,
            GroupMemberPointerInitialize {
                token_program_id: token_program.clone(),
                mint: mint.clone(),
            },
        ),
        Some(ctx.accounts.program_authority.key()),
        Some(token_mint_key),
    )?;

    initialize_mint2(
        CpiContext::new(token_program_id, InitializeMint2 { mint: mint.clone() }),
        0,
        &ctx.accounts.program_authority.key(),
        None,
    )?;

    token_member_initialize(CpiContext::new_with_signer(
        token_program_id,
        TokenMemberInitialize {
            program_id: token_program.clone(),
            member: mint.clone(),
            member_mint: mint.clone(),
            member_mint_authority: ctx.accounts.program_authority.to_account_info(),
            group: ctx.accounts.group_mint.to_account_info(),
            group_update_authority: ctx.accounts.program_authority.to_account_info(),
        },
        signer_seeds,
    ))?;

    token_metadata_initialize(
        CpiContext::new_with_signer(
            token_program_id,
            TokenMetadataInitialize {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.program_authority.to_account_info(),
                mint_authority: ctx.accounts.program_authority.to_account_info(),
                mint: mint.clone(),
            },
            signer_seeds,
        ),
        args.name,
        args.symbol,
        args.uri,
    )?;

    token_metadata_update_field(
        CpiContext::new_with_signer(
            token_program_id,
            TokenMetadataUpdateField {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.program_authority.to_account_info(),
            },
            signer_seeds,
        ),
        Field::Key(SECP256R1_METADATA_KEY.to_string()),
        secp_pubkey_b64,
    )?;

    for (key, value) in transfer_config_placeholder_fields() {
        token_metadata_update_field(
            CpiContext::new_with_signer(
                token_program_id,
                TokenMetadataUpdateField {
                    program_id: token_program.clone(),
                    metadata: mint.clone(),
                    update_authority: ctx.accounts.program_authority.to_account_info(),
                },
                signer_seeds,
            ),
            Field::Key(key.to_string()),
            value.to_string(),
        )?;
    }

    token_metadata_update_field(
        CpiContext::new_with_signer(
            token_program_id,
            TokenMetadataUpdateField {
                program_id: token_program.clone(),
                metadata: mint.clone(),
                update_authority: ctx.accounts.program_authority.to_account_info(),
            },
            signer_seeds,
        ),
        Field::Key(LAST_TRANSFER_SLOT_METADATA_KEY.to_string()),
        initial_last_transfer_slot_value(),
    )?;

    associated_token::create_idempotent(CpiContext::new(
        ctx.accounts.associated_token_program.key(),
        Create {
            payer: ctx.accounts.payer.to_account_info(),
            associated_token: ctx.accounts.owner_token_account.to_account_info(),
            authority: ctx.accounts.owner.to_account_info(),
            mint: mint.clone(),
            system_program: ctx.accounts.system_program.to_account_info(),
            token_program: ctx.accounts.token_program.to_account_info(),
        },
    ))?;

    mint_to(
        CpiContext::new_with_signer(
            token_program_id,
            MintTo {
                mint: mint.clone(),
                to: ctx.accounts.owner_token_account.to_account_info(),
                authority: ctx.accounts.program_authority.to_account_info(),
            },
            signer_seeds,
        ),
        1,
    )?;

    set_authority(
        CpiContext::new(
            token_program_id,
            SetAuthority {
                account_or_mint: ctx.accounts.owner_token_account.to_account_info(),
                current_authority: ctx.accounts.owner.to_account_info(),
            },
        ),
        AuthorityType::CloseAccount,
        Some(ctx.accounts.program_authority.key()),
    )?;

    Ok(())
}
