export const SDK_SURFACE = {
  webAuthn: {
    credentialId: "33 bytes = authenticator passkey; 16 bytes = platform echoed placeholder (recovery runs)",
    rpcRequired:
      "Kit Rpc required for startAuthentication(message, { rpc }) recovery and on-chain browser taps (authenticatePasskeyForSecp256r1Verify, authenticatePasskeyForTransfer)",
    recovery:
      "When multiple keys verify, disambiguates via initialized PhygitalToken PDA on-chain",
    authenticatePasskey:
      "Shared helper for on-chain flows: options.transceive → authenticateWithApdu; else authenticateWithWebauthn. Used by authenticatePasskeyForTransfer, authenticatePasskeyForSecp256r1Verify.",
  },
  admin: [
    "getCreateConfigInstruction",
    "getSetAdminInstruction",
    "getSetIssuerInstruction",
    "getSetMinterInstruction",
    "getClosePhygitalTokenInstruction",
    "findAdminConfigPda",
  ],
  initialize: [
    "getInitializeInstruction",
    "findPhygitalTokenPda",
    "findAdminConfigPda",
    "parseSecp256r1Pubkey",
  ],
  assignMint: [
    "getAssignMintInstruction",
    "findPhygitalTokenPda",
    "findAdminConfigPda",
  ],
  transfer: [
    "beginTransfer({ rpc, secp256r1Pubkey, rpId? })",
    "authenticatePasskeyForTransfer(session, { transceive?, origin? })",
    "completeTransfer",
  ],
  removeLinkedWallet: ["getRemoveLinkedWalletInstruction"],
  verifyComposable: [
    "buildMessageHash",
    "authenticatePasskeyForSecp256r1Verify({ rpc?, messageHash, rpId?, origin?, transceive? })",
    "buildSecp256r1VerifyInstruction",
  ],
  verification: [
    "startAuthentication(message, { rpc?, transceive? })",
    "verifyResponse({ expectedMessage, response })",
  ],
  onChainComposition: {
    client: [
      "buildMessageHash",
      "authenticatePasskeyForSecp256r1Verify({ rpc?, messageHash, transceive?, rpId?, origin? })",
      "buildSecp256r1VerifyInstruction",
    ],
    transaction: ["secp256r1_verify", "your_program_instruction"],
    program: "CPI verify via VerifyCpiBuilder",
    optionalBindings: {
      expected_rp_id: "Option<String> — omit to skip; SHA256(rpId) must match authenticatorData[0..32]",
      expected_origins: "Option<Vec<String>> — omit to skip; when set, clientDataJSON.origin must match one entry",
    },
  },
  tokenLookup: [
    "findPhygitalTokenPda",
    "findAdminConfigPda",
    "fetchPhygitalTokensByLinkedWallet",
    "fetchPhygitalTokenByIdentifier",
    "fetchPhygitalTokenByMint",
  ],
  generated: [
    "getInitializeInstruction",
    "getAssignMintInstruction",
    "getSetLinkedWalletInstruction",
    "getVerifyInstruction",
    "getRemoveLinkedWalletInstruction",
    "getCreateConfigInstruction",
    "getSetAdminInstruction",
    "getSetIssuerInstruction",
    "getSetMinterInstruction",
    "getClosePhygitalTokenInstruction",
    "fetchPhygitalToken",
    "fetchAdminConfig",
    "findAdminConfigPda",
    "PhygitalToken",
    "AdminConfig",
    "PhygitalTokenType",
  ],
  rustClient: {
    crate: "phygital-token-client",
    path: "packages/rust/phygital-token",
    cpi: [
      "ClosePhygitalTokenCpi",
      "ClosePhygitalTokenCpiBuilder",
      "VerifyCpi",
      "VerifyCpiBuilder",
      "VerifyInstructionArgs",
      "AssignMintCpi",
      "AssignMintCpiBuilder",
      "SetLinkedWalletCpi",
      "SetLinkedWalletCpiBuilder",
      "RemoveLinkedWalletCpi",
      "RemoveLinkedWalletCpiBuilder",
      "CreateConfigCpi",
      "CreateConfigCpiBuilder",
      "SetIssuerCpi",
      "SetIssuerCpiBuilder",
      "SetMinterCpi",
      "SetMinterCpiBuilder",
    ],
    types: ["PhygitalToken", "AdminConfig", "Secp256r1VerifyArgs", "PhygitalTokenType"],
    roles: {
      admin: "sole AdminConfig.admin — create_config signer; set_admin / set_issuer / set_minter / close_phygital_token",
      issuer: "sole AdminConfig.issuer — may call initialize",
      minter: "sole AdminConfig.minter — may call assign_mint",
    },
    tokenTypes: {
      Permanent: "discriminant 0 — linked wallet required at init; starts locked; set_linked_wallet / remove rejected",
      Bearer: "freely transferable by passkey when unlocked; tokens with linked wallet at init start locked",
      Controlled: "lock after claim; forfeit via remove_linked_wallet before next transfer",
    },
  },
} as const;
